name: readsms
description: A flutter plugin that reads incoming SMS on device as a broadcast stream.
version: 0.0.2+2
homepage: "https://github.com/Ayush783/readsms_plugin"

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: "<=2.0.6"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ayush783.readsms
        pluginClass: ReadsmsPlugin
      ios:
        pluginClass: ReadsmsPlugin

